/* Generated By:JavaCC: Do not edit this line. AusdruckConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AusdruckConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int PRO = 6;
  /** RegularExpression Id. */
  int SUTR = 7;
  /** RegularExpression Id. */
  int FINAL = 8;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int IDENT = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "\" \"",
    "<NUMBER>",
    "<PRO>",
    "<SUTR>",
    "\"final\"",
    "\"int\"",
    "<IDENT>",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"=\"",
    "\",\"",
    "\"\"",
  };

}
