/* Generated By:JavaCC: Do not edit this line. MiniJavaProgramConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaProgramConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int MAL = 6;
  /** RegularExpression Id. */
  int GETEILT = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int MINUS = 9;
  /** RegularExpression Id. */
  int FINAL = 10;
  /** RegularExpression Id. */
  int INT = 11;
  /** RegularExpression Id. */
  int FUNC = 12;
  /** RegularExpression Id. */
  int VOID = 13;
  /** RegularExpression Id. */
  int WHILE = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int PRINT = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int RETURN = 18;
  /** RegularExpression Id. */
  int IDENT = 19;
  /** RegularExpression Id. */
  int COMPOP = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "\" \"",
    "<NUMBER>",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"final\"",
    "\"int\"",
    "\"func\"",
    "\"void\"",
    "\"while\"",
    "\"if\"",
    "\"print\"",
    "\"else\"",
    "\"return\"",
    "<IDENT>",
    "<COMPOP>",
    "\";\"",
    "\"=\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
  };

}
