PARSER_BEGIN(U2_A12)
public class U2_A12 {
public static void main (String args []) {
U2_A12 parser = new U2_A12(System.in);
try {
parser.start();
} catch (ParseException e) {
System.err.println(e);
}
}
}
PARSER_END(U2_A12)
SKIP:
{ "\r" | "\n" | "\t" }
TOKEN:
{
<LETTER : ["A"-"Z"]>
|
<NUMBER : ["1"-"9"] (["0"-"9"]){0,3} >
|
<KENNZEICHEN : (<LETTER>){1,3} " - " (<LETTER>){1,2} " " <NUMBER> >
}
void start():
{}
{
<KENNZEICHEN>
<EOF> { System.out.println("Kennzeichen formal ok!"); }
}
