/* Generated By:JavaCC: Do not edit this line. U2_A12Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface U2_A12Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 4;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int KENNZEICHEN = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "<LETTER>",
    "<NUMBER>",
    "<KENNZEICHEN>",
  };

}
